// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// mediate_helper
void mediate_helper(Rcpp::Environment& env);
RcppExport SEXP _UmediationThread_mediate_helper(SEXP envSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::Environment& >::type env(envSEXP);
    mediate_helper(env);
    return R_NilValue;
END_RCPP
}
// mediate_helper_variable_exporter
void mediate_helper_variable_exporter(Rcpp::Environment& env);
RcppExport SEXP _UmediationThread_mediate_helper_variable_exporter(SEXP envSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::Environment& >::type env(envSEXP);
    mediate_helper_variable_exporter(env);
    return R_NilValue;
END_RCPP
}
// threaded_mediate_helper
void threaded_mediate_helper(Rcpp::Environment& env, long long int num_threads);
RcppExport SEXP _UmediationThread_threaded_mediate_helper(SEXP envSEXP, SEXP num_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::Environment& >::type env(envSEXP);
    Rcpp::traits::input_parameter< long long int >::type num_threads(num_threadsSEXP);
    threaded_mediate_helper(env, num_threads);
    return R_NilValue;
END_RCPP
}
// test_pseudo_dataframe
Eigen::MatrixXd test_pseudo_dataframe(Rcpp::Environment& env, std::string var_name, std::string treat_name, std::string mediator_name);
RcppExport SEXP _UmediationThread_test_pseudo_dataframe(SEXP envSEXP, SEXP var_nameSEXP, SEXP treat_nameSEXP, SEXP mediator_nameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::Environment& >::type env(envSEXP);
    Rcpp::traits::input_parameter< std::string >::type var_name(var_nameSEXP);
    Rcpp::traits::input_parameter< std::string >::type treat_name(treat_nameSEXP);
    Rcpp::traits::input_parameter< std::string >::type mediator_name(mediator_nameSEXP);
    rcpp_result_gen = Rcpp::wrap(test_pseudo_dataframe(env, var_name, treat_name, mediator_name));
    return rcpp_result_gen;
END_RCPP
}
// test
void test(Rcpp::Environment& env);
RcppExport SEXP _UmediationThread_test(SEXP envSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::Environment& >::type env(envSEXP);
    test(env);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_UmediationThread_mediate_helper", (DL_FUNC) &_UmediationThread_mediate_helper, 1},
    {"_UmediationThread_mediate_helper_variable_exporter", (DL_FUNC) &_UmediationThread_mediate_helper_variable_exporter, 1},
    {"_UmediationThread_threaded_mediate_helper", (DL_FUNC) &_UmediationThread_threaded_mediate_helper, 2},
    {"_UmediationThread_test_pseudo_dataframe", (DL_FUNC) &_UmediationThread_test_pseudo_dataframe, 4},
    {"_UmediationThread_test", (DL_FUNC) &_UmediationThread_test, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_UmediationThread(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
