// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// mediate_helper
void mediate_helper(Rcpp::Environment& env);
RcppExport SEXP _Umediation_mediate_helper(SEXP envSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::Environment& >::type env(envSEXP);
    mediate_helper(env);
    return R_NilValue;
END_RCPP
}
// mediate_helper_variable_exporter
void mediate_helper_variable_exporter(Rcpp::Environment& env);
RcppExport SEXP _Umediation_mediate_helper_variable_exporter(SEXP envSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::Environment& >::type env(envSEXP);
    mediate_helper_variable_exporter(env);
    return R_NilValue;
END_RCPP
}
// threaded_mediate_helper
void threaded_mediate_helper(Rcpp::Environment& env, long long int num_threads);
RcppExport SEXP _Umediation_threaded_mediate_helper(SEXP envSEXP, SEXP num_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::Environment& >::type env(envSEXP);
    Rcpp::traits::input_parameter< long long int >::type num_threads(num_threadsSEXP);
    threaded_mediate_helper(env, num_threads);
    return R_NilValue;
END_RCPP
}
// test
void test(Rcpp::Environment& env);
RcppExport SEXP _Umediation_test(SEXP envSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::Environment& >::type env(envSEXP);
    test(env);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Umediation_mediate_helper", (DL_FUNC) &_Umediation_mediate_helper, 1},
    {"_Umediation_mediate_helper_variable_exporter", (DL_FUNC) &_Umediation_mediate_helper_variable_exporter, 1},
    {"_Umediation_threaded_mediate_helper", (DL_FUNC) &_Umediation_threaded_mediate_helper, 2},
    {"_Umediation_test", (DL_FUNC) &_Umediation_test, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_Umediation(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
